// Mocks generated by Mockito 5.4.5 from annotations
// in dog_breeds_mobile_app/test/ui/breed/breed_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:dog_breeds_mobile_app/data/repositories/breeds_repository.dart'
    as _i2;
import 'package:dog_breeds_mobile_app/data/services/api/model/breed_api_model.dart'
    as _i3;
import 'package:dog_breeds_mobile_app/ui/breed/view_models/breed_viewmodel.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBreedsRepository_0 extends _i1.SmartFake
    implements _i2.BreedsRepository {
  _FakeBreedsRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBreed_1 extends _i1.SmartFake implements _i3.Breed {
  _FakeBreed_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BreedInfoViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockBreedInfoViewModel extends _i1.Mock
    implements _i4.BreedInfoViewModel {
  MockBreedInfoViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BreedsRepository get breedsRepository =>
      (super.noSuchMethod(
            Invocation.getter(#breedsRepository),
            returnValue: _FakeBreedsRepository_0(
              this,
              Invocation.getter(#breedsRepository),
            ),
          )
          as _i2.BreedsRepository);

  @override
  List<dynamic> get breedSubBreeds =>
      (super.noSuchMethod(
            Invocation.getter(#breedSubBreeds),
            returnValue: <dynamic>[],
          )
          as List<dynamic>);

  @override
  set breedSubBreeds(List<dynamic>? _breedSubBreeds) => super.noSuchMethod(
    Invocation.setter(#breedSubBreeds, _breedSubBreeds),
    returnValueForMissingStub: null,
  );

  @override
  List<dynamic> get breedImages =>
      (super.noSuchMethod(
            Invocation.getter(#breedImages),
            returnValue: <dynamic>[],
          )
          as List<dynamic>);

  @override
  set breedImages(List<dynamic>? _breedImages) => super.noSuchMethod(
    Invocation.setter(#breedImages, _breedImages),
    returnValueForMissingStub: null,
  );

  @override
  String get breedRandomImage =>
      (super.noSuchMethod(
            Invocation.getter(#breedRandomImage),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#breedRandomImage),
            ),
          )
          as String);

  @override
  set breedRandomImage(String? _breedRandomImage) => super.noSuchMethod(
    Invocation.setter(#breedRandomImage, _breedRandomImage),
    returnValueForMissingStub: null,
  );

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  set isLoading(bool? _isLoading) => super.noSuchMethod(
    Invocation.setter(#isLoading, _isLoading),
    returnValueForMissingStub: null,
  );

  @override
  set error(String? _error) => super.noSuchMethod(
    Invocation.setter(#error, _error),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Breed get breed =>
      (super.noSuchMethod(
            Invocation.getter(#breed),
            returnValue: _FakeBreed_1(this, Invocation.getter(#breed)),
          )
          as _i3.Breed);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<void> getBreedTotalInfoFromRepo(_i3.Breed? breed) =>
      (super.noSuchMethod(
            Invocation.method(#getBreedTotalInfoFromRepo, [breed]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
